version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list_db
    ports:
      - "5432:5432"
    volumes:
      - todo_list_db:/var/lib/postgresql/data

volumes:
  todo_list_db: